### ISSUE TITLE
What is meaning of this parameter?

### ISSUE THREAD

**Issue by taylorcoderer** [nkoub/multinetx#2]
I want to draw a Multi layer network by using Python. The expected graph likes this: 
![oky9v](https://user-images.githubusercontent.com/13978535/37772812-c0117274-2e16-11e8-8aeb-f1d652939e6e.png)
This is my command:
![default](https://user-images.githubusercontent.com/13978535/37773115-a5ceb9c0-2e17-11e8-975f-859376b4b4d1.PNG)
mst_pearson,mst_kendall,mst_tail are my original networks, I want to use them to establish a three-layers multilayer network. But the error is that:
![image](https://user-images.githubusercontent.com/13978535/37773155-c15593f8-2e17-11e8-8351-253b087801f1.png)
What is that error mean? How could I fix it?

**Comment by nkoub** [comment]
The parameter layer_horizontal_shift defines a horizontal displacement of the relative position of the layers in the horizontal axis.

The library is written for Python2.7 and uses
networkx.__version__
'2.0'
numpy.__version__
'1.12.1'

Can you plot each network separately using the networkx? If you can so, then it is straightforward to plot them in a multiplex.
