### ISSUE TITLE
Support for networks with different number of nodes in each layer

### ISSUE THREAD

**Issue by sulheim** [nkoub/multinetx#3]
Seems like there have to be equally many nodes in each layer. A generalization, aloowing different number of nodes would be nice.

**Comment by nkoub** [comment]
solved by Ines Carrasco. Please check the the updated code

**Comment by MonicaRavipudi** [comment]
Hi , 
Using this code for MultilayerGraph from " https://github.com/InesCarrasco/multinetx/blob/master/classes/multilayer.py " is giving the error "TypeError: 'list' object cannot be interpreted as an integer" at pos = mx.get_position( ... )
Please advice.
